import '@/app/ui/global.css'
import { inter } from '@/app/ui/fonts';
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    template: '%s | Generative Learning',
    default: 'Generative Learning',
  },
  description: 'Generated by electron-Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased h-screen flex flex-col`}>
        {children}
      </body>
    </html>
  )
}
